//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickEV_Website.Views.ASPX
{


    public partial class CariKegiatan
    {

        /// <summary>
        /// Welcome_CariKegiatan_Container_Text1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label Welcome_CariKegiatan_Container_Text1;

        /// <summary>
        /// Welcome_CariKegiatan_Container_Text2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label Welcome_CariKegiatan_Container_Text2;

        /// <summary>
<<<<<<< HEAD
        /// TotalAktivitas_Text control.
=======
        /// Welcome_CariKegiatan_Container_Text3 control.
>>>>>>> 1891c195683b65b551b3212e1c8f0e573a2cfff6
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
<<<<<<< HEAD
        protected global::System.Web.UI.WebControls.Label TotalAktivitas_Text;

        /// <summary>
        /// AktivitasMenunggu control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label AktivitasMenunggu;
=======
        protected global::System.Web.UI.WebControls.Label Welcome_CariKegiatan_Container_Text3;
>>>>>>> 1891c195683b65b551b3212e1c8f0e573a2cfff6
    }
}
