//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickEV_Website.Views.ASPX
{


    public partial class TentangKamiPage
    {

        /// <summary>
        /// Welcome_TentangKami_Column1_Text1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label Welcome_TentangKami_Column1_Text1;

        /// <summary>
        /// Welcome_TentangKami_Column1_Text2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label Welcome_TentangKami_Column1_Text2;

        /// <summary>
        /// Welcome_TentangKami_Column2_Text1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label Welcome_TentangKami_Column2_Text1;

        /// <summary>
        /// Welcome_TentangKami_Column2_Text2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label Welcome_TentangKami_Column2_Text2;

        /// <summary>
        /// CeritaKami_TentangKami_Header control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label CeritaKami_TentangKami_Header;

        /// <summary>
        /// CeritaKami_TentangKami_Text control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label CeritaKami_TentangKami_Text;

        /// <summary>
        /// AmbilBagianBtn control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button AmbilBagianBtn;

        /// <summary>
        /// Mission_TentangKami_VisiHeader control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label Mission_TentangKami_VisiHeader;

        /// <summary>
        /// Mission_TentangKami_MisiHeader control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label Mission_TentangKami_MisiHeader;

        /// <summary>
        /// Mission_TentangKami_VisiText control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label Mission_TentangKami_VisiText;

        /// <summary>
        /// Mission_TentangKami_MisiText control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label Mission_TentangKami_MisiText;

        /// <summary>
        /// Fitur_TentangKami_Header control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label Fitur_TentangKami_Header;

        /// <summary>
        /// Fitur_TentangKami_CariKegiatan_RightContent_Header control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label Fitur_TentangKami_CariKegiatan_RightContent_Header;

        /// <summary>
        /// Fitur_TentangKami_CariKegiatan_RightContent_Text control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label Fitur_TentangKami_CariKegiatan_RightContent_Text;

        /// <summary>
        /// Fitur_TentangKami_CariOrganisasi_LeftContent_Header control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label Fitur_TentangKami_CariOrganisasi_LeftContent_Header;

        /// <summary>
        /// Fitur_TentangKami_CariOrganisasi_LeftContent_Text control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label Fitur_TentangKami_CariOrganisasi_LeftContent_Text;

        /// <summary>
        /// Fitur_TentangKami_Donasi_RightContent_Header control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label Fitur_TentangKami_Donasi_RightContent_Header;

        /// <summary>
        /// Fitur_TentangKami_Donasi_RightContent_Text control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label Fitur_TentangKami_Donasi_RightContent_Text;
    }
}
